"use client";

console.warn(
  "⚠️ Avoid importing components from 'index.js' for better performance. This practice is deprecated and may be removed in the future."
);

export * as _Builtin from "./_Builtin";
export * from "./devlinkContext";
export * from "./interactions";
export * from "./utils";
export * from "./devlink";
export * from "./Accordion";
export * from "./Border";
export * from "./Button";
export * from "./Card";
export * from "./CardBody";
export * from "./CmsBlogForSlider";
export * from "./CprCard";
export * from "./CprContainer";
export * from "./CprCustomHeader";
export * from "./CprFooter";
export * from "./CprHeader";
export * from "./CprInforBanner";
export * from "./CprLink";
export * from "./CprMainBanner";
export * from "./CprPromoBanner";
export * from "./CprRatingComment";
export * from "./CprSecondFooter";
export * from "./CustomCode";
export * from "./DevLinkProvider";
export * from "./Eyebrow";
export * from "./FlexCardComponent";
export * from "./Footer";
export * from "./GridColumn";
export * from "./GridRow";
export * from "./HeaderNavigator";
export * from "./Heading";
export * from "./Icon";
export * from "./IconSize";
export * from "./Image";
export * from "./ImageFit";
export * from "./InlineVideo";
export * from "./LearnMoreComponent";
export * from "./List";
export * from "./Modal";
export * from "./Nav";
export * from "./NavBanner";
export * from "./OldBenefitSection";
export * from "./OutlineBtn";
export * from "./PlainText";
export * from "./RatingImagesComponents";
export * from "./RepairCard";
export * from "./RepairInformationCard";
export * from "./RichText";
export * from "./SearchField";
export * from "./Section";
export * from "./SectionBadge";
export * from "./SiteHeader";
export * from "./Slider";
export * from "./Spacer";
export * from "./SwiperSlide";
export * from "./UseLocationIconText";
export * from "./WhyChooseUsCard";
